# Generated by Django 6.0.1 on 2026-01-17 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_membros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_donos', to=settings.AUTH_USER_MODEL),
        ),
    ]
