# Generated by Django 6.0.1 on 2026-01-18 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_card_ordem_alter_card_titulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coluna',
            options={},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='arquivado',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='atualizado_em',
        ),
        migrations.AddField(
            model_name='card',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='conteudo_original',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='prompt_refinado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='titulo',
            field=models.CharField(default='Nova Tarefa', max_length=100),
        ),
        migrations.AlterField(
            model_name='coluna',
            name='cor',
            field=models.CharField(default='#F1F5F9', max_length=7),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_dono', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='projetos_membro', to=settings.AUTH_USER_MODEL),
        ),
    ]
