# Generated by Django 6.0.1 on 2026-01-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_card_options_alter_coluna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
