# Generated by Django 6.0.1 on 2026-01-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Modo')),
                ('slug', models.SlugField(help_text='Identificador unico (ex: bug-hunter)', unique=True)),
                ('description', models.CharField(max_length=200, verbose_name='Descrição Curta')),
                ('system_instruction', models.TextField(verbose_name='Prompt do Sistema (Instrução)')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
