# Generated by Django 6.0.1 on 2026-01-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(help_text='Breve descrição do que ele faz', max_length=200)),
                ('prompt_sistema', models.TextField(help_text="Ex: 'Você é um especialista em React. Critique o código...'")),
                ('temperatura', models.FloatField(default=0.7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ActionTemplate',
        ),
    ]
